### ISSUE TITLE
image upload

### ISSUE THREAD

**Issue by thelxinoe** [thelxinoe/foodsharing-production#19]
Implementing it using meteor-files

https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo-simplest-upload
https://github.com/VeliovGroup/Meteor-Files#files-for-meteor

**Comment by ClaaziX** [comment]
Want me to give this a crack?

**Comment by thelxinoe** [comment]
I've already started work on this. Maybe try squash some bugs? Or take a look at meteor methods and try doing some of the message insertion stuff?

**Comment by thelxinoe** [comment]
That libs total shit so I'm going to move back to meteor collectionfs

**Comment by thelxinoe** [comment]
Got the basics working.
